### ISSUE TITLE
⚠️ <Code> MDX/CSS bug

### ISSUE THREAD

**Issue by spencerlepine** [spencerlepine/spencerlepine.com#42]
Doing 'code' will highlight as code on the blog, but it will include the quotes. This makes it harder to read the blog posts

**Comment by spencerlepine** [comment]
```css
code::before, code::after {
  display: none;
}

:not(pre) > code.language-text {
  color: rgb(85, 85, 85);
  background: rgb(204, 204, 204) !important;
}
```
